### ISSUE TITLE
#010 getPhotos() function only returns latest 100 data record

### ISSUE THREAD

**Issue by koki25ando** [koki25ando/FlickrAPI#11]
pulling the same 100 photos from the account

this can be resolved by specifying &page= parameter but not officially suported

**Comment by elipousson** [comment]
Since `get_photos` and `get_photos_search` access the same API and since `get_photos_search` supports the "per_page" and "page" parameters to address this issue, I think it probably makes sense to merge get_photos_search into `get_photos` and add a new `get_user_photos` function that is a simplified version of `get_photos_search`.

If this sounds good to you, I think this could be a good major change before resubmitting the package to CRAN for review. Let me know what you think or I'll ping you when I have a chance to create a pull request with the changes.

**Comment by elipousson** [comment]
I took the first step on this by updating get_photos to call get_photos_search: https://github.com/koki25ando/FlickrAPI/commit/45aa2382a05e9a81abc20b5700e9864e161076e0 

I hope it is OK that I'm just going ahead and making these changes! If you'd prefer I make pull requests so we can do a collaborative review, please let me know – but I figured it may be less work for you if I just go ahead, use my judgement if it is a major change that needs review, and document any changes I make.

**Comment by koki25ando** [comment]
@elipousson thanks for your cooperation
these new changes look good to me, and nice updates to make before CRAN resubmit!
I'm interested these changes so please create a pull requests if you don't mind

**Comment by elipousson** [comment]
Will do!

**Comment by elipousson** [comment]
Since `getPhotos()` now supports both the `per_page` and `sort` parameters, I don't think this is still an active issue with the package so I'm going to go ahead and close it. I'll open a separate issue with a checklist for CRAN re-submission when I have a chance!
